spring:
  application:
    name: mab-schedule
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:lEtfbOBZDtAg4v7}
    url: ${DB_URL:jdbc:postgresql://192.241.149.226:5432/db_mab}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8013
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
