spring:
  application:
    name: mab-schedule
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:lEtfbOBZDtAg4v7}
    url: ${DB_URL:jdbc:postgresql://192.241.149.226:5432/db_mab}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://192.241.149.226:8080/realms/mab-manitos
          jwk-set-uri: http://192.241.149.226:8080/realms/mab-manitos/protocol/openid-connect/certs
server:
  port: 8013
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://192.241.149.226:9411/api/v2/spans
minio:
  bucket:
    appointment: ${MINIO_BUCKET_APPOINTMENT:appointment-docs}