spring:
  application:
    name: mab-schedule
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:lEtfbOBZDtAg4v7}
    url: ${POSTGRES_URL:jdbc:postgresql://192.241.149.226:5432/db_mab}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM:http://192.241.149.226:8080/realms/mab-manitos}
          jwk-set-uri: ${KEYCLOAK_OPEN_ID:http://192.241.149.226:8080/realms/mab-manitos/protocol/openid-connect/certs}
server:
  port: ${PORT:8013}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka/}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER_URI:http://192.241.149.226:9411/api/v2/spans}
minio:
  bucket:
    appointment: ${MINIO_BUCKET_APPOINTMENT:appointment-docs}

security-constraints:
  constraints:
    - auth-roles:
        - paciente
      security-collections:
        - name: appointments-for-patient
          patterns:
            - /api/v1/appointment/patient/**
          methods:
            - GET

    - auth-roles:
        - doctor
      security-collections:
        - name: appointment
          patterns:
            - /api/v1/appointment/patient/**
          methods:
            - POST

    - auth-roles:
        - permitAll
      security-collections:
        - name: periods
          patterns:
            - /api/v1/period/periods
          methods:

    - auth-roles:
        - permitAll
      security-collections:
        - name: schedule-doctor
          patterns:
            - /api/v1/schedule-doctor/**
          methods:
            - GET

    - auth-roles:
        - permitAll
      security-collections:
        - name: schedule-doctor-doctor
          patterns:
            - /api/v1/schedule-doctor/doctor/**
          methods:
            - GET

    - auth-roles:
        - doctorJefe
        - doctor
      security-collections:
        - name: unavailable-schedule
          patterns:
            - /api/v1/schedule-doctor/unavailable-schedule/**
          methods:
            - POST

    - auth-roles:
        - permitAll
      security-collections:
        - name: unavailable-schedule
          patterns:
            - /api/v1/schedule-doctor/unavailable-schedule/**
          methods:
            - GET

    - auth-roles:
        - doctorJefe
        - doctor
      security-collections:
        - name: appointments-for-doctor
          patterns:
            - /api/v1/appointment/doctor/**
          methods:
            - GET
