spring:
  application:
    name: mab-schedule
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1216316}
    url: jdbc:postgresql://localhost:5432/manitos_bmsc_2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://192.241.149.226:8080/realms/mab-manitos
          jwk-set-uri: http://192.241.149.226:8080/realms/mab-manitos/protocol/openid-connect/certs
server:
  port: 8013
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
